### PR TITLE
Push release tags to the CDN

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
When a Github release is created on this repo, The release version will be deployed to the CDN under the release version

Eg. `https://cdn.ons.gov.uk/sdc/v1.0.0/img/icons/icons--accordion.svg`

### CODE REVIEW

**Comment by armstrongb** [comment]
@jonnyshaw89 is this a supplement to the existing pipeline?

**Comment by jonnyshaw89** [comment]
@armstrongb yes, http://concourse.dev.eq.ons.digital/teams/main/pipelines/sdc-global-design-patterns

**Comment by armstrongb** [comment]
Please update the readme.md with details of the `tag` path for use and details of how Git tags vs merge to master short hash CDN versions differ.

**Comment by jonnyshaw89** [comment]
@armstrongb Readme updated.
Merge if your happy.

**Pull request merged**
