### PR TITLE
Initial draft of implementing file upload input

### LINKED ISSUE #35: Add input type of file
Add the file upload component as used in RAS mvp.

### PR DESCRIPTION
**Pull request by armstrongb**
### Context of this PR

This is the initial work on integrating the file upload component as created for RAS mvp.

### How to test

- Checkout this branch and use `yarn start` to preview the Upload component in '[Form elements](http://localhost:3000/components/detail/upload)'.
- Review `/components/02-form-elements/upload/_upload.scss`.
- Review `/components/02-form-elements/upload/upload.hbs`.
- Cross-browser test.

### Issue
Resolves #35

### CODE REVIEW

**Comment by shahi645** [comment]
@armstrongb should the upload work no matter where you click, even on the text part ?

**Comment by jonnyshaw89** [comment]
@armstrongb is this PR in progress?

**Comment by armstrongb** [comment]
@shahi645 yes it should, including the label and label description.

**Comment by hamishtaplin** [comment]
Focus style could do with some love:

screenshot 2017-12-04 09 08 18

**Comment by armstrongb** [comment]
@hamishtaplin these should be resolved now. Can you review when you have time? thanks.

**Pull request merged**
