### PR TITLE
Add duration as multiple input fields

### PR DESCRIPTION
**Pull request by saedwards**
Pattern located under Form elements > Duration

### CODE REVIEW

**Comment by will-madebymoon** [comment]
screen shot 2018-03-20 at 11 31 41

The label 'Time' should be 18px from the fields see other labels. Therer should be more padding around Hours

**Comment by will-madebymoon** [comment]
Need to add some padding around 'Hours' I would suggest 0.5rem(9px) either side

**Comment by will-madebymoon** [comment]
Width should be 67px

**Comment by saedwards** [comment]
@will-madebymoon Latest changes committed.

**Comment by will-madebymoon** [comment]
This is almost there in my components i've got the filed and label coming out at 151 in width where these are 126

**Comment by MIslam92** [comment]
@bennpearson @will-madebymoon one of you guys can merge this right?

**Comment by will-madebymoon** [comment]
screen shot 2018-05-22 at 13 36 38

Current the labels have a fixed width and need to have a 0.5rem padding either side. See 'Months' as an example.

**Pull request merged**
