### PR TITLE
Refactored accordion to allow for simple variant

### PR DESCRIPTION
**Pull request by boxadesign**
### What is the context of this PR?
Replace `accordion`, `definition` , `guidance`, `feedback`  and `details-toggle` with a single component - `collapsible`.

This refactoring came from the need to bring the inline feedback form from runner into the pattern library. This was a standalone component that was redesigned to make it consistent with similar show/hide components in the PL. This created 4 separate components, each with it's own `scss`, `js` and `html`, all carrying out similar functionality.

Decided to create a maintainable, single code base for dealing with such components.

In this PR are two small fixes to the `icons` component and the character limit js for the `textarea`

### How to review 

Review the implementation of the code works for the pattern library.
Review the non-js fallback.
Review against accessibility requirements.

### CODE REVIEW

**Comment by armstrongb** [comment]
The chevron placement in F'fox (61.0.2) on Mac seems to be out.
#### Firefox

feedback-chevron-alignment-ffox_61-0-2 _osx

#### Chrome
feedback-chevron-alignment-chrome _osx

**Comment by armstrongb** [comment]
Definition seems to have lost its chevron

**Comment by armstrongb** [comment]
@boxadesign should we include some analytics events on the cancel button of the feedback form? I can see some on the submit and the reveal but not the dismiss. 

/cc @charlotte-hirst

**Comment by boxadesign** [comment]
@armstrongb This is ready for full review

**Pull request merged**
